### ISSUE TITLE
Feature Request: Increment and decrement rectangle 

### ISSUE THREAD

**Issue by raveensrk** [jdtsmith/speedrect#3]
It would be nice to have increment and decrement rectangle selection similar to vim.

```
1 -> 2
2 -> 3
3 -> 4
4 -> 5

10 -> 9
11 -> 10
12 -> 11
13 -> 12
```

I use vim to do this all the time. Cant find equivalent for emacs.

**Comment by jdtsmith** [comment]
Is it always a range of numbers?  Or increment _any_ arbitrary numbers?

**Comment by jdtsmith** [comment]
`#` pulls the column(s) as a vector into calc, where it is easy to perform arbitrary operations.  @oantolin, is there a way you know to pull the top calc stack matrix back into a rectangle?

**Comment by oantolin** [comment]
There is `calc-copy-to-buffer`, but it's quite what we want here because it writes out the full calc matrix syntax, not just the entries. I don't think calc has a command that does exactly what you'd need here.

**Comment by oantolin** [comment]
Oh, calc has a variety of display formats for matrices! You can use `v [` to toggle the presence of brackets in the display of matrices. For a matrix of more than one column that still leaves commas, but for a column vector that leaves just the numbers. And `calc-copy-to-buffer` uses whatever display format you currently have.

**Comment by jdtsmith** [comment]
Thanks.  I found `v [` and `v ,` to turn off brackets and commas, then `C-u y` yanks to the last buffer.  The main issue is `calc-copy-to-buffer` calls `(kill-region (region-beginning) (region-end))`, and so can't do rectangle inserts.  The manual even says:

>  Also, note that this command replaces a linear region of text (as grabbed by ‘C-x * g’), not a rectangle (as grabbed by ‘C-x * r’).

A good addition to calc would be to do rectangle replacement if 1) the target buffer is in rectangle-mark-mode, and 2) the rectangles number of rows matches the number of rows (/lines) in the calc text. Maybe it's possible to finesse from the speedrect side. I'll leave this open as an invitation to anyone who wants to look into a smooth rect -> calc -> rect round trip approach.  I can see that workflow as being very powerful.   Something like:

1. Mark rectangle in calc buffer at top of stack.
2. `extract-rectangle` (saving in a variable)
3. Back in the original buffer, insert the saved rectangle (a list of lines) over the top of the marked rectangle. I don't think there's a command for this (yank does _not_ replace the rectangle) but it would be easy to roll with `delete-rectangle-line`.

**Comment by oantolin** [comment]
That would indeed be a good addition to calc. And there's even precedent: @hmelman suggested that `calc-grab-region` call `calc-grab-rectangle` if `rectangle-mark-mode` is on, and that's now in Emacs 28!

**Comment by hmelman** [comment]
I haven't wanted to increment or decrement a rectangle, though I do use `markdown-cleanup-list-numbers` a lot.  Maybe that's useful here too.

**Comment by jdtsmith** [comment]
OK, that wasn't so hard to do from the speedrect side.  I added the shortcut `m`, which yanks the matrix from the top of the calc stack (checking that it has the right number of rows).  This overwrites the current rectangle.  

So for @raveensrk's simple case:

- `#` grab one (or more!) marked columns as a rectangle in calc
-  (in calc) `1 +` adds 1 to each element
- `q` to bury calc buffer
- `m` to overwrite the marked rectangle with the new value

But of course you can do a _lot_ more than adding 1, once the data are in calc as a matrix.  Probably you should `v [` and `v ,` in your calc, to avoid getting extra brackets and commas in your columns.  

I'll leave this open a bit longer in case people have ideas on how to improve this.  Already looking useful.

**Comment by raveensrk** [comment]
@jdtsmith I tried this but the last `m` command does not seem to work. This is what I get at the end as final result.

![image](https://user-images.githubusercontent.com/40625660/224630119-cfd65ee7-e70a-46ee-8396-30b0285c2c99.png)

**Comment by jdtsmith** [comment]
You probably have the old version still in place.  Either restart or recompile the file (`M-x emacs-lisp-byte-compile-and-load` is useful). `?` should show the `m` command in there.

**Comment by raveensrk** [comment]
@jdtsmith I still see this issue. This time, when I press m, the rectangle is deleted. The Calc matrix is not placed into the buffer.

This is what i did,


```
1
2
3
```

```
C-x SPC, select the rectangle
#
1+
q
m
```

**Comment by raveensrk** [comment]
```
;;; Straight
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
(setq package-enable-at-startup nil)
;; (setq straight-use-package-by-default t)

(setq use-package-compute-stastics t)

(straight-use-package 'use-package)


(use-package speedrect
  :straight (speedrect :type git :host github :repo "jdtsmith/speedrect")
  )
```

This is my init file.

**Comment by jdtsmith** [comment]
What's happening in the calc buffer during this?

**Comment by raveensrk** [comment]
@jdtsmith This is what I see.

[https://youtu.be/RcFCjvrbEQE](https://youtu.be/RcFCjvrbEQE)
