### ISSUE TITLE
calc sum bindings

### ISSUE THREAD

**Issue by hmelman** [jdtsmith/speedrect#4]
FWIW I would use `_` and `:` for `calc-grab-sum-across` and `calc-grab-sum-down` respectively.  This mirrors calc's own bindings and IMHO is easier to remember which is which.

**Comment by jdtsmith** [comment]
Thanks, good idea, done.  Are there any natural bindings for the new `[m] yank-mat  yank matrix from top of calc stack, overwriting selected rec`?

**Comment by hmelman** [comment]
Sorry, my calc knowledge is quite limited, so I'd have to search calc doc/sources to find out.

**Comment by jdtsmith** [comment]
No worries I basically never used calc until yesterday!  Very useful for quick column munging though.
