### ISSUE TITLE
ELPA/MELPA?

### ISSUE THREAD

**Issue by minad** [jdtsmith/speedrect#7]
I've seen your release 0.5 at https://old.reddit.com/r/emacs/comments/1fzb73r/speedrect_v05_modal_tools_during_rectangle/. This made me wonder if you want to put this on ELPA or MELPA?

**Comment by jdtsmith** [comment]
It might be good to do so.  I have wondered whether I should use a transient instead. Have you used it?  Any feedback/ideas for new functions?

**Comment by jdtsmith** [comment]
I've submitted to ELPA.

**Comment by manuel-uberti** [comment]
Just chiming in to say "thank you!". This package makes rectangle interactions much more comfortable.

**Comment by jdtsmith** [comment]
Thanks, glad you are enjoying.
